
LENGTH_RECORD = 101
LENGTH_ERR = "LENGTH OF RECORD IS GREATER THAN 101 CHARACTERS."
LENGTH_ACCNT_AMT = 35
LENGTH_ACCNT_AMT_ERR = "RECORD IS NOT HAVING PROPER LENGTH OF ACCOUNT TYPE OR ACCOUNT NUMBER OR AMOUNT."
ACCOUNT_CHK_DIGIT_ERR = "ACCOUNT NUMBER OF THE RECORD IS NOT HAVING PROPER CHECK DIGIT."
ACCOUNT_NUMERIC_ERR = "ACCOUNT NUMBER IS NOT NUMERIC."
ACCOUNT_NUMBER_ZERO_ERR = "ACCOUNT NUMBER OF THE RECORD IN THE FILE IS ZERO."
ACCOUNT_NUMBER_CHARS_ERR = "ACCOUNT NUMBER LENGTH IS NOT WITHIN LIMIT OF 11 TO 13 CHARACTERS."
AMOUNT_NUMERIC_ERR = "AMOUNT NUMBER IS NOT NUMERIC."
FILE_WRITE_ERR = "THERE IS ISSUE IN WRITING REPORT."
FILE_PROCESSING_EXCEPTION = "THERE IS ISSUE IN FILE PROCESSING."
MAX_CR_DR_AMOUNT_ERR = "AMOUNT IS GREATER THAN MAXIMUM ALLOWED LIMIT 3000 Cr."
